{{- if .Values.consumer.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: "{{ include "confluent-performance-suite.fullname" . }}-consumer"
  labels:
    {{- include "confluent-performance-suite.labels" . | nindent 4 }}
    type: consumer
spec:
  selector:
    {{- include "confluent-performance-suite.selectorLabels" . | nindent 4 }}
    type: consumer
  ports:
    - name: jmx
      port: 7071
{{- end }}
