{{- if .Values.producer.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: "{{ include "confluent-performance-suite.fullname" . }}-producer"
  labels:
    {{- include "confluent-performance-suite.labels" . | nindent 4 }}
    type: producer
spec:
  selector:
    {{- include "confluent-performance-suite.selectorLabels" . | nindent 4 }}
    type: producer
  ports:
    - name: jmx
      port: 7071
{{- end }}
