{{- if .Values.consumer.enabled -}}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: "{{ include "confluent-performance-suite.fullname" . }}-consumer"
  labels:
    {{- include "confluent-performance-suite.labels" . | nindent 4 }}
spec:
  serviceName: "{{ include "confluent-performance-suite.fullname" . }}-consumer"
  replicas: {{ .Values.consumer.count }}
  selector:
    matchLabels:
      {{- include "confluent-performance-suite.selectorLabels" . | nindent 6 }}
      type: consumer
  template:
    metadata:
      annotations:
        timestamp: {{ now | quote }}
      labels:
        {{- include "confluent-performance-suite.selectorLabels" . | nindent 8 }}
        type: consumer
    spec:
      initContainers:
      - name: topics
        image: {{ .Values.consumer.image }}
        command:
        - /bin/sh
        - -c
        - |
          kafka-topics \
            --if-not-exists \
            --topic {{ .Values.topic.name }}  \
            --create \
            --bootstrap-server {{ .Values.broker.url }} \
            --replication-factor {{ .Values.topic.replicationFactor }}  \
            --partitions {{ .Values.topic.partitions }}  \
            --command-config /mnt/kafka.properties
        volumeMounts:
        - name: kafka-properties
          mountPath: /mnt
      containers:
      - name: consumer
        image: {{ .Values.consumer.image }}
        command:
        - /bin/sh
        - -c
        - |
          kafka-consumer-perf-test \
            --topic {{ .Values.topic.name }}  \
            --bootstrap-server {{ .Values.broker.url }} \
            --messages {{ .Values.consumer.messagesCount }} \
            --consumer.config /mnt/kafka.properties \
            --print-metrics && sleep infinity
        volumeMounts:
        - name: kafka-properties
          mountPath: /mnt
      volumes:
        - name: kafka-properties
          secret:
            secretName: "{{ include "confluent-performance-suite.fullname" . }}-kafka-client-config"
{{- end }}
